export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const FETCH_INDIA_CASES = 'FETCH_INDIA_CASES';
export const FETCH_WORLD_CASES = 'FETCH_WORLD_CASES';
export const FETCH_STATE_DISTRICT_WISE_CASES =
  'FETCH_STATE_DISTRICT_WISE_CASES';
export const FETCH_STATE_DISTRICT_WISE_ZONES =
  'FETCH_STATE_DISTRICT_WISE_ZONES';
